### ISSUE TITLE
spark I can't run the example jar on it. Is that the wrong version? Both are spark2.3

### ISSUE THREAD

**Issue by liangrui1988** [ZuInnoTe/hadoopoffice#54]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.FileFormat.$init$(Lorg/apache/spark/sql/execution/datasources/FileFormat;)V
	at org.zuinnote.spark.office.excel.DefaultSource.<init>(DefaultSource.scala:115)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:335)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
	at org.zuinnote.spark.office.example.excel.SparkReadXls$.main(SparkReadXls.scala:22)
	at org.zuinnote.spark.office.example.excel.SparkReadXls.main(SparkReadXls.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:906)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/05/30 16:45:31 INFO SparkContext: Invoking stop() from shutdown hook
19/05/30 16:45:31 INFO SparkUI: Stopped Spark web UI at http://hdp01:4040

**Comment by jornfranke** [comment]
你好
Can you please provide the command that you use and a link to the Jar?
Can you please try to build the example yourself and then to run it?
Are you sure that it is Spark 2.30 with Scala 2.11 and not Spark 2.4 with Scala 2.12?
It looks like there is a version mismatch in the libraries.
谢谢

**Comment by liangrui1988** [comment]
Is my question - packages com. Making. Zuinnote: spark - hadoopoffice - ds_2. 12:1. 3.1 I write the wrong version.But I want to know how much MB XLS data our plugin can handle at most.We are now dealing with customers' XLS, which are all very large, 245MB, which hung up my computer at my local place.I'm going to try it out on the test cluster.We use python pandas to CSV, which takes about 10 minutes locally.I want to use this plugin to optimize, I wonder if it can improve the processing speed?thank you

**Comment by jornfranke** [comment]
You can use the option hadoopoffice.read.lowFootprint to optimize memory (see other options https://github.com/ZuInnoTe/hadoopoffice/wiki/Hadoop-File-Format). The library helps you to read a lot of excel files on a cluster in parallel.

**Comment by jornfranke** [comment]
another possibility to increase performance is to specify the Schema of the Excel file and thus do not infer it (reduces processing time by 50%).

**Comment by liangrui1988** [comment]
Oh, I'll check it out later.But if I run it on a spark cluster, it won't work. Right?
Tip diagnostics: the User class threw the exception: org). Apache hadoop. Mapred. FileAlreadyExistsException: the Output directory HDFS: / / hdp01:8020 / User/spark/office/excel/Output already exists.Is it because cluster multiple servers output on one HDFS?How do you optimize it?


spark-submit --master yarn-cluster  --executor-cores 2 --num-executors 3 --driver-memory 4G --executor-memory 2G  --packages org.apache.hadoop:hadoop-yarn-server-tests:2.7.0,com.github.zuinnote:spark-hadoopoffice-ds_2.11:1.3.1 --class org.zuinnote.spark.office.example.excel.SparkScalaExcelInDataSource /home/spark/officeexec/jar/example-ho-spark-scala-ds-excelin_2.11-0.1.jar /user/spark/office/excel/inputbig /user/spark/office/excel/output

How do we deal with this? I want to see how long he takes。
thanks

**Comment by liangrui1988** [comment]
I'm going to crash, 245MB XLS.Error, small file can be displayed for processing

[spark@presto jar]$ spark-submit --master yarn-cluster  --executor-cores 2 --num-executors 5 --driver-memory 8G --executor-memory 2G  --packages org.apache.hadoop:hadoop-yarn-server-tests:2.7.0,com.github.zuinnote:spark-hadoopoffice-ds_2.11:1.3.1 --class org.zuinnote.spark.office.example.excel.SparkScalaExcelInDataSource /home/spark/officeexec/jar/example-ho-spark-scala-ds-excelin_2.11-0.1.jar /user/spark/office/excel/inputbig /user/spark/office/excel/output


19/05/30 20:31:00 INFO SharedState: Warehouse path is 'file:/hadoop/yarn/local/usercache/spark/appcache/application_1556423179598_0572/container_e40_1556423179598_0572_02_000002/spark-warehouse'.
19/05/30 20:31:00 INFO YarnSchedulerBackend$YarnDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (10.200.102.193:53176) with ID 4
19/05/30 20:31:00 INFO BlockManagerMasterEndpoint: Registering block manager hdp03:43788 with 912.3 MB RAM, BlockManagerId(4, hdp03, 43788, None)
19/05/30 20:31:01 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
19/05/30 20:31:01 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 357.6 KB, free 4.1 GB)
19/05/30 20:31:02 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 31.9 KB, free 4.1 GB)
19/05/30 20:31:02 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on hdp02:42367 (size: 31.9 KB, free: 4.1 GB)
19/05/30 20:31:02 INFO SparkContext: Created broadcast 0 from broadcast at DefaultSource.scala:157
19/05/30 20:31:02 INFO OfficeReader: Using standard API to parse Excel file
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000657200000, 2125463552, 0) failed; error='Cannot allocate memory' (errno=12)

Failing this attempt. Failing the application.
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: default
	 start time: 1559218929951
	 final status: FAILED
	 tracking URL: http://hdp02:8088/cluster/app/application_1556423179598_0572
	 user: spark
19/05/30 20:31:38 INFO Client: Deleted staging directory hdfs://hdp01:8020/user/spark/.sparkStaging/application_1556423179598_0572
Exception in thread "main" org.apache.spark.SparkException: Application application_1556423179598_0572 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1230)
	at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1585)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:906)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/05/30 20:31:38 INFO ShutdownHookManager: Shutdown hook called
19/05/30 20:31:38 INFO ShutdownHookManager: Deleting directory /tmp/spark-6eb0430a-41d1-429b-b41b-87a4be0587b9
19/05/30 20:31:38 INFO ShutdownHookManager: Deleting directory /tmp/spark-6bd52d9d-64c8-49d2-864d-8004f30a9f99
[spark@presto jar]$ 

 val start_t = Calendar.getInstance().getTime.getTime
    println("start_" + start_t)
    val df = sqlContext.read
      .format("org.zuinnote.spark.office.excel")
      .option("hadoopoffice.read.locale.bcp47", "us")
      .option("hadoopoffice.read.header.read", true).option("read.spark.simpleMode", true)
      .load(inputFile)
    println(df.printSchema())
    println(df.count())
    println(df.show())
    val ent_t = Calendar.getInstance().getTime.getTime
    println("end_" + ent_t)
    println("end_start_" + (ent_t - start_t))

**Comment by jornfranke** [comment]
Can you please check also the driver and executor logs?
You forgot the option hadoopoffice.read.lowFootprint: .option("hadoopoffice.read.lowFootprint","true")
Then, if you provide a schema you save 50% of the time.

**Comment by jornfranke** [comment]
Can we close this issue?
