### ISSUE TITLE
Error loading Microsoft Excel (.xls) file: `java.io.IOException: Stream is closed!` 

### ISSUE THREAD

**Issue by krishnapriawan** [ZuInnoTe/hadoopoffice#80]
Hi,

We are encountering following error when it comes to reading Excel `.xls` (sample file:
[Breakfast.xls](https://github.com/ZuInnoTe/hadoopoffice/files/14138630/Breakfast.xls)):
```
java.lang.Exception: java.io.IOException: Stream is closed!
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:489)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:549)
Caused by: java.io.IOException: Stream is closed!
	at org.apache.hadoop.fs.BufferedFSInputStream.getPos(BufferedFSInputStream.java:56)
	at org.apache.hadoop.fs.FSDataInputStream.getPos(FSDataInputStream.java:75)
	at org.zuinnote.hadoop.office.format.mapreduce.AbstractSpreadSheetDocumentRecordReader.getFilePosition(AbstractSpreadSheetDocumentRecordReader.java:255)
	at org.zuinnote.hadoop.office.format.mapreduce.AbstractSpreadSheetDocumentRecordReader.getProgress(AbstractSpreadSheetDocumentRecordReader.java:282)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigRecordReader.getProgress(PigRecordReader.java:158)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.getProgress(MapTask.java:540)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:562)
	at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:270)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

My FileInputFormat Implementation:
```
public class ExcelFileInputFormat extends org.zuinnote.hadoop.office.format.mapreduce.ExcelFileInputFormat {

	private String sheetName;
	private String skipInputHeader;

	public ExcelFileInputFormat(String sheetName, boolean skipInputHeader) {
		this.sheetName = sheetName;
		this.skipInputHeader = skipInputHeader ? "true" : "false";
	}

	@Override
	public RecordReader<Text, ArrayWritable> createRecordReader(InputSplit split, TaskAttemptContext ctx) {
		/** Create reader **/
		// send configuration option to ms excel. The format of the Excel (old vs new)
		// is detected automatically
		ctx.getConfiguration().set(HadoopOfficeReadConfiguration.CONF_MIMETYPE, "ms-excel");
		if (sheetName != null && !sheetName.isEmpty()) {
			ctx.getConfiguration().set("hadoopoffice.read.sheets", this.sheetName);
		}
		ctx.getConfiguration().set("hadoopoffice.read.header.read", this.skipInputHeader);
		return new ExcelRecordReader(ctx.getConfiguration(), (FileSplit) split);

	}

	public void configure(Configuration conf) {
		// nothing here
	}

	/**
	 * Unfortunately, we cannot split Excel documents correctly. Apache POI/library
	 * requires full documents.
	 * Nevertheless, most of the time you have anyway small (smaller than default
	 * HDFS blocksize) Office documents that can be processed fast.
	 * Hence, you should put them in Hadoop Archives (HAR) either uncompressed or
	 * compressed to reduce load on namenode.
	 *
	 */
	@Override
	protected boolean isSplitable(JobContext context, Path file) {
		return false;
	}

}
```

`pom.xml`:
```
        <dependency>
            <groupId>com.github.zuinnote</groupId>
            <artifactId>hadoopoffice-fileformat</artifactId>
            <version>1.7.0</version>
        </dependency>
```
In addition, the implementation works with `.xlsx` file format.
I'm using Hadoop `2.8.3` on Java `1.8`
Appreciate if anyone can help me to debug this error.

Thank you!

**Comment by jornfranke** [comment]
Thanks for reporting this. Just a question: Why would you want to extend the existing format. I do not see any new functionality that you add.

Then, can you provide more code? In particular, how you use the format in your own application?

**Comment by krishnapriawan** [comment]
Thank you for your response and for raising this important question. Initially, I extended the existing format because I aimed to customize the configuration more granularly than what seemed possible through the standard mechanisms e.g. `sheetName` and `skipInputHeader`. However, upon reflecting on your query and revisiting the documentation and capabilities of the library, I now recognize that utilizing the `configure()` method offers a cleaner and more straightforward approach to achieve the desired customization without altering the existing format. Thanks for the pointer!

FileLoader implementation (adopted from Pig library [here](https://github.com/apache/pig/blob/4bf875077dbd0f9c7baed23cd0d33d9c93c973fe/contrib/piggybank/java/src/main/java/org/apache/pig/piggybank/storage/CSVExcelStorage.java)), snippet as follows:
```
import org.zuinnote.hadoop.office.format.common.dao.SpreadSheetCellDAO;

public class ExcelFileLoader extends LoadFunc {
  public ExcelFileLoader(String fields, String sheetName, String options) { }

  @Override
  public void setLocation(String location, Job job) throws IOException {
    FileInputFormat.setInputPaths(job, location);
  }

  public InputFormat getInputFormat() throws IOException {
    return new ExcelFileInputFormat(this.sheetName, this.skipInputHeader);
  }

  @Override
  public void prepareToRead(RecordReader recordReader, PigSplit pigSplit) throws IOException {
    this.reader = recordReader;
    if (tagPath) {
      sourcePath = ((FileSplit) pigSplit.getWrappedSplit()).getPath();
    }
  }

  @Override
  public Tuple getNext() throws IOException {

    mProtoTuple = new ArrayList<Object>();

    getNextInQuotedField = false;
    boolean evenQuotesSeen = true;
    boolean sawEmbeddedRecordDelimiter = false;
    byte[] buf = null;

    if (!mRequiredColumnsInitialized) {
      if (udfContextSignature != null) {
        Properties p = UDFContext.getUDFContext().getUDFProperties(this.getClass());
        mRequiredColumns = (boolean[]) ObjectSerializer.deserialize(p.getProperty(udfContextSignature));
      }
      mRequiredColumnsInitialized = true;
    }

    try {
      int recordLen = 0;
      getNextFieldID = 0;

      while (sawEmbeddedRecordDelimiter || getNextFieldID == 0) {
        Text value = null;
        if (sawEmbeddedRecordDelimiter) {

          int prevLineLen = recordLen + 1;

          byte[] prevLineSaved = Arrays.copyOf(buf, prevLineLen);
          prevLineSaved[prevLineLen - 1] = RECORD_DEL;

          if (!reader.nextKeyValue()) {
            return null;
          }
          value = parseSpreadSheetCellValue(reader.getCurrentValue());
          recordLen = value.getLength();
          buf = value.getBytes();

          byte[] prevLineAndContinuation = Arrays.copyOf(prevLineSaved, prevLineLen + recordLen);

          System.arraycopy(buf, 0, prevLineAndContinuation, prevLineLen, recordLen);

          buf = prevLineAndContinuation;

          mProtoTuple.clear();
          getNextInQuotedField = false;
          evenQuotesSeen = true;
          getNextFieldID = 0;
          recordLen = prevLineAndContinuation.length;

        } else {
          if (!reader.nextKeyValue()) {
            return null;
          }
          value = parseSpreadSheetCellValue(reader.getCurrentValue());

          buf = value.getBytes();
          getNextFieldID = 0;
          recordLen = value.getLength();
        }

        nextTupleSkipChar = false;

        ByteBuffer fieldBuffer = ByteBuffer.allocate(recordLen);

        sawEmbeddedRecordDelimiter = processOneInRecord(evenQuotesSeen,
            buf, recordLen, fieldBuffer);

      
      } // end while

    } catch (InterruptedException e) {
      int errCode = 6018;
      String errMsg = "Error while reading input";
      throw new ExecException(errMsg, errCode,
          PigException.REMOTE_ENVIRONMENT, e);
    }

    Tuple t = tupleFactory.newTupleNoCopy(mProtoTuple);
    return t;
  }

  private Text parseSpreadSheetCellValue(Object currentValue) {
    ArrayWritable valueArrayWritable = (ArrayWritable) currentValue;
    SpreadSheetCellDAO[] valueArray = (SpreadSheetCellDAO[]) valueArrayWritable.get();
    List<String> list = new ArrayList<String>();
    if (tagPath) {
      list.add(sourcePath.toUri().toString());
    }
    for (int i = 0; i < valueArray.length; i++) {
      SpreadSheetCellDAO currentSpreadSheetCellDAO = valueArray[i];
      if (currentSpreadSheetCellDAO != null) {
        list.add("\"" + currentSpreadSheetCellDAO.getFormattedValue().replaceAll("\"", "\"\"") + "\"");
      } else {
        list.add(StringUtils.EMPTY);
      }
    }
    return new Text(StringUtils.join(list, ","));
  }
}
```

Following are the Pig script we execute:
```
copy_of_load_24840 = LOAD 'schemadb://USER_SFTP_CONNECTION@dummy/user/Breakfast.xls' USING com.org.pig.piggybank.storage.ExcelFileLoader('id,name,price,description,calories', 'Breakfast', '-skip_input_header') AS (id:int, name:chararray, price:float, description:chararray, calories:int);
copy_of_load = FOREACH copy_of_load_24840 GENERATE (int)(id) AS id:int, (chararray)(name) AS name:chararray, (float)(price) AS price:float, (chararray)(description) AS description:chararray, (int)(calories) AS calories:int;
```

Appreciate the help!

**Comment by jornfranke** [comment]
You need to set hadoop options using the [Pig set command](https://pig.apache.org/docs/latest/cmds.html#set).

e.g. SET hadoopoffice.read.sheets 'mysheetname'

This will set the Hadoop Configuration that is automatically picked up by the InputFormat.

You find all possible options here: https://github.com/ZuInnoTe/hadoopoffice/wiki/Hadoop-File-Format#configure

**Comment by krishnapriawan** [comment]
Hey there!

Thanks a bunch for pointing me towards the Hadoop options with the Pig set command. Super helpful! 😊 Just wanted to let you know that after digging a bit deeper, it turns out the trouble was actually with the SFTP library I'm using to load files, not the HadoopOffice setup.

So, I'm gonna go ahead and close this issue now. Really appreciate your help in getting to the bottom of this!

Cheers!
